### ISSUE TITLE
NotImplementedError when using .display()

### ISSUE THREAD

**Issue by schakalakka** [altair-viz/altair_viewer#39]
When running 
```
import pandas as pd
import altair as alt
import mid_utils as mu
import altair_viewer
alt.renderers.enable('altair_viewer')
...
...
baz = alt.Chart(bar).mark_bar().encode(x='upper', y='Häufigkeit', color='HVM:N')
altair_viewer.display(baz)
```
in IPython (within Pycharm) I get the following exception:

```
Exception in thread Thread-21:
Traceback (most recent call last):
  File "D:\miniconda\envs\mid17_schemes\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "D:\miniconda\envs\mid17_schemes\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:\miniconda\envs\mid17_schemes\lib\site-packages\altair_data_server\_background_server.py", line 66, in start_server
    httpd.listen(port=port, address=address)
  File "D:\miniconda\envs\mid17_schemes\lib\site-packages\tornado\tcpserver.py", line 152, in listen
    self.add_sockets(sockets)
  File "D:\miniconda\envs\mid17_schemes\lib\site-packages\tornado\tcpserver.py", line 165, in add_sockets
    self._handlers[sock.fileno()] = add_accept_handler(
  File "D:\miniconda\envs\mid17_schemes\lib\site-packages\tornado\netutil.py", line 279, in add_accept_handler
    io_loop.add_handler(sock, accept_handler, IOLoop.READ)
  File "D:\miniconda\envs\mid17_schemes\lib\site-packages\tornado\platform\asyncio.py", line 100, in add_handler
    self.asyncio_loop.add_reader(fd, self._handle_events, fd, IOLoop.READ)
  File "D:\miniconda\envs\mid17_schemes\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError
NotImplementedError
```

Installed versions: 

altair | 4.1.0 |  
altair_data_server | 0.4.1 |  
altair_viewer | 0.3.0 |  

Do I something wrong or is this a bug with IPython/Pycharm?

**Comment by schakalakka** [comment]
Yes, this workaround fixes it. Thank you for your help! 

As an alternative: I started to use the Jupyter integration in Pycharm with the same renderer where the problem does not occur. Maybe it does not use Tornado? I don't know.
